name: Pylint

on:
  schedule:
    # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
     - cron:  '30 16 * * *' # 默认在每天 UTC 16:30 （北京时间 0:30）执行
jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest
run main.py
