name: Pylint

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  
  schedule:
  # Github Action 使用世界标准时间（UTC），北京时间（UTC+8）转换为世界标准时需要减去8小时
    - cron:  '30 23 * * *' # 默认在每天 UTC 7:30 （北京时间 0:30）执行

jobs:
  USER_01:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r enail.txt
        pip install -r datetime.txt
        pip install -r smtplib.txt
    - name: Run script

      run: python main.py
